# 指定语言 https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "6"
branches:
  only:
    - master
script:
  - npm test
notifications:
  webhooks:
    urls:
      - https://www.travisbuddy.com/
    on_success: never
    on_failure: always
